[develop]
script_dir=$base/lib/MARTIN_Jetson_Package

[install]
install_scripts=$base/lib/MARTIN_Jetson_Package

[options.entry_points]
console_scripts =
    april_tag_node = MARTIN_Jetson_Package.scripts.AprilTag_node:main
    camera_node = MARTIN_Jetson_Package.scripts.camera_node:main
    sybil_node = MARTIN_Jetson_Package.scripts.SYBIL_node:main

